cluster.name: "eleme-cluster"
node.name: "eleme-node-1"
node.master: true
node.data: true

network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300

discovery.type: single-node

# 禁用安全特性 (开发环境)
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.watcher.enabled: false
xpack.ml.enabled: false

# 内存设置
bootstrap.memory_lock: true

# 索引设置
action.destructive_requires_name: true

# 日志设置
logger.org.elasticsearch.discovery: INFO
logger.org.elasticsearch.cluster.service: INFO

# 线程池设置
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# 自动创建索引
action.auto_create_index: true 