server:
  port: 8901

spring:
  application:
    name: test-simple-service
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 