server:
  port: 8002

spring:
  application:
    name: eleme-business-service
  
  config:
    import: "optional:nacos:eleme-business-service.yml"
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        file-extension: yml
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        shared-configs:
          - data-id: eleme-business-service.yml
            group: DEFAULT_GROUP
            refresh: true
    
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8722
      eager: true
      log:
        dir: logs/sentinel
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: business-service-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        ds2:
          nacos:
            server-addr: localhost:8848
            dataId: business-service-degraded-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eleme_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: eleme
    password: eleme123
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          config:
            multi-statement-allow: true

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: redis123
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000ms

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Swagger配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: 饿了么商家服务API
    description: 商家信息查询、搜索、分类等功能
    version: 1.0.0
    contact:
      name: 开发团队
      email: dev@eleme.com

# 日志配置
logging:
  level:
    org.example: DEBUG
    com.baomidou.mybatisplus: DEBUG
  file:
    name: ../infrastructure/logs/business-service/business-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 